# Generated by Django 2.2.10 on 2020-02-13 19:26

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.TextField(default='')),
                ('url', models.TextField(default='')),
                ('title', models.TextField(default='')),
                ('author', models.TextField(default='')),
                ('summary', models.TextField(default='')),
                ('body', djongo.models.fields.ArrayField(model_container=models.TextField())),
                ('tags', djongo.models.fields.ArrayField(model_container=models.TextField())),
            ],
        ),
    ]
