name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test
      run: |
        cd crawler
        python api.py flask start &
        sleep 10
        wget http://127.0.0.1:5000/tag/china -O test_tag.json
        wget http://127.0.0.1:5000/author/honderich -O test_author.json
        wget http://127.0.0.1:5000/word/computer -O test_notfound.json
        wget --content-on-error http://127.0.0.1:5000/api/something -O test_404.json
        ls -lR --ignore=__pycache__
        echo -e "Content of test_tag.json:\n" && \
          python -m json.tool test_tag.json && \
          echo -e "--------------------------\n"
        echo -e "Content of test_author.json:\n" && \
          python -m json.tool test_author.json && \
          echo -e "--------------------------\n"
        echo -e "Content of test_notfound.json:\n" && \
          python -m json.tool test_notfound.json && \
          echo "--------------------------\n"
        echo -e "Content of test_404.json:\n" && \
          python -m json.tool test_404.json && \
          echo -e "--------------------------\n"
